# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPANPLUS-Shell-Default-Plugins-RT
version:      0.01
version_from: lib/CPANPLUS/Shell/Default/Plugins/RT.pm
installdirs:  site
requires:
    CPANPLUS:                      0.059
    Locale::Maketext::Simple:      0
    LWP:                           0
    Params::Check:                 0.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
